services:
  faucet-server:
    extends:
      file: docker-compose.yml
      service: faucet-server
    ports:
      - "${SMF_WEBBACKEND_PORT}:${SMF_WEBBACKEND_PORT}"
    environment:
      SMF_BACKEND_NETWORK_DECIMALS: 12
      SMF_BACKEND_RPC_ENDPOINT: "https://rococo-rpc.polkadot.io/"
      SMF_WEBBACKEND_DRIP_AMOUNT: "100"
