networks:
  faucet-e2e:
    external: true
services:
  matrix:
    container_name: e2e-matrix
    image: matrixdotorg/synapse:v1.76.0
    ports:
      - "8008:8008"
    networks:
      - faucet-e2e
    volumes:
      - "./matrix_data:/data"
    environment:
      SYNAPSE_SERVER_NAME: "parity.io"
      SYNAPSE_REPORT_STATS: "no"
    command: "run"
